spring.application.name=IappMessenger

#185.104.248.176
#server.address=localhost
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost/postgres
#spring.datasource.url=jdbc:postgresql://185.104.248.176:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=dalvrogi

server.max-http-header-size=10000000
jwt.secret=very_secret_key_very_secret_key_123456

# automatic create tables (pgadmin) IMPORTANT!!!
spring.jpa.hibernate.ddl-auto=update
# sql visible
spring.jpa.show-sql=true
# special output format
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# spring.data.redis.password=dalvrogi

# ТОМCAT: "Я не буду дочитывать больше 2MB мусора"
server.tomcat.max-swallow-size=2MB
# Лимит размера HTML form POST
server.tomcat.max-http-form-post-size=2MB